/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: MartianDays (https://sketchfab.com/aeries)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/spacex-starship-a8a0b69f776841a1a465cd9fb3762fd2
title: SpaceX Starship
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/starship/scene.gltf')
  return (
    <mesh position={[.7, .7, .7]} scale={.000005}>
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 42.38, -5293.18]} rotation={[-Math.PI, 0, 0]}>
          <group rotation={[-Math.PI, 0, 0]}>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Bow_Window001_Starship_0.geometry}
                material={nodes.Bow_Window001_Starship_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Primary_Hull001_Starship_0.geometry}
                material={nodes.Primary_Hull001_Starship_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Cargo_Doors001_Starship_0.geometry}
                material={nodes.Cargo_Doors001_Starship_0.material}
              />
            </group>
            <group position={[0, 0, 123.11]} rotation={[0, 0, Math.PI / 2]} scale={[65.53, 65.53, 81.73]}>
              <mesh
                geometry={nodes.SeaLev_Raptors_LP001_Starship_0.geometry}
                material={nodes.SeaLev_Raptors_LP001_Starship_0.material}
              />
            </group>
            <group rotation={[0, 0, -Math.PI / 2]} scale={[65.53, 65.53, 81.73]}>
              <mesh
                geometry={nodes.Vacuum_Raptors_LP001_Starship_0.geometry}
                material={nodes.Vacuum_Raptors_LP001_Starship_0.material}
              />
            </group>
            <group position={[-1.13, -0.26, 0]} rotation={[0, 0, -Math.PI / 6]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Cargo_DropBoxes001_Starship_0.geometry}
                material={nodes.Cargo_DropBoxes001_Starship_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Cabin_WindowInset001_Starship_0.geometry}
                material={nodes.Cabin_WindowInset001_Starship_0.material}
              />
            </group>
            <group rotation={[0, 0, Math.PI / 2]} scale={[100, 100, 100]}>
              <mesh
                geometry={nodes.Cabin_Windows001_Starship_0.geometry}
                material={nodes.Cabin_Windows001_Starship_0.material}
              />
            </group>
          </group>
        </group>
      </group>
    </group>
    </mesh>
  )
}

useGLTF.preload('/scene.gltf')
